language: csharp
solution: Kubernetes.DotNet.sln
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore Kubernetes.DotNet.sln
  - mono nuget.exe install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Kubernetes.DotNet.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./src/Kubernetes.DotNet.Test/bin/Release/Kubernetes.DotNet.Test.dll
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh $MAJOR_VERSION_NUMBER $MINOR_VERSION_NUMBER $TRAVIS_BUILD_NUMBER $NUGET_API_KEY
  on:
    branch: master